version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: sgc
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sgc"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - "8080:8080"

volumes:
  pg_data:

